services:
  graylog:
    # Sử dụng image Graylog phiên bản 6.0.5
    image: graylog/graylog:6.0.5
    container_name: graylog
    # Định nghĩa phụ thuộc vào dịch vụ opensearch và mongodb
    depends_on:
      opensearch:
        condition: "service_started" # Khởi động khi opensearch đã sẵn sàng
      mongodb:
        condition: "service_started" # Khởi động khi mongodb đã sẵn sàng
    entrypoint: "/usr/bin/tini -- wait-for-it elasticsearch:9200 -- /docker-entrypoint.sh"
    environment:
      - GRAYLOG_NODE_ID_FILE=/usr/share/graylog/data/config/node-id
      - GRAYLOG_HTTP_BIND_ADDRESS=0.0.0.0:9000 # Địa chỉ bind cho giao diện HTTP
      - GRAYLOG_ELASTICSEARCH_HOSTS=http://opensearch:9200 # Địa chỉ của OpenSearch
      - GRAYLOG_MONGODB_URI=mongodb://mongodb:27017/graylog # URI kết nối MongoDB
      - GRAYLOG_REPORT_DISABLE_SANDBOX=true # Vô hiệu hóa sandbox cho báo cáo
      - GRAYLOG_PASSWORD_SECRET=34loSp3QrC7vGn1L5p4VysY8fe1aIJOOEFLFKWGD4kc6KkCXpAq7bd2aIJsJl47hDmuV0Mmr6IByFP2HVg5vspGovOWFFvZ5 # Bí mật dùng để mã hóa
      - GRAYLOG_ROOT_PASSWORD_SHA2=065e0ac84427a42a55a56f786ae125255d0c0455deb763a96fb4f13be6ebc8c9 # Mật khẩu root mã hóa SHA2 (pass: minhtenlaquang)
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/ # URI bên ngoài cho giao diện web
      - GRAYLOG_SERVER_JAVA_OPTS=-Xms2g -Xmx2g
      - GRAYLOG_ROOT_TIMEZONE=Asia/Ho_Chi_Minh # Múi giờ cho tài khoản root
    ports:
      - "9000:9000/tcp" # Cổng HTTP cho giao diện web
      - "5044:5044/udp" # Cổng cho nhận log từ Filebeat udp
      - "5044:5044/tcp" # Cổng cho nhận log từ Filebeat tcp
      - "5140:5140/udp" # Cổng cho nhận log từ syslog udp
      - "5140:5140/tcp" # Cổng cho nhận log từ syslog tcp
      - "12201:12201/tcp" # Cổng cho nhận log từ GELF TCP
      - "12201:12201/udp" # Cổng cho nhận log từ GELF UDP
      - "13301:13301/tcp" # Cổng tùy chỉnh (thay thế cho dịch vụ khác) tcp
      - "13301:13301/udp" # Cổng tùy chỉnh (thay thế cho dịch vụ khác) udp
      - "13302:13302/tcp" # Cổng tùy chỉnh khác tcp
      - "13302:13302/udp" # Cổng tùy chỉnh khác udp
    volumes:
      - "graylog_data:/usr/share/graylog/data:rw" # Volume cho dữ liệu của Graylog
      - "graylog_plugin:/usr/share/graylog/plugin:rw" # Volume cho journal của Graylog
    restart: on-failure # Tự động khởi động lại nếu gặp lỗi
    networks:
      - graylog_net
    #deploy:
    #  resources:
    #    limits:
    #      cpus: "2.0"
    #      memory: "4G"
    #    reservations:
    #      cpus: "1.0"
    #      memory: "2G"

  opensearch:
    # Sử dụng image OpenSearch phiên bản 2.12.0
    image: opensearchproject/opensearch:2.12.0
    container_name: opensearch
    environment:
      - OPENSEARCH_JAVA_OPTS=-Xms4g -Xmx4g # Thiết lập bộ nhớ Java cho OpenSearch
      - processbuffer_processors=6
      - bootstrap.memory_lock=true # Khóa bộ nhớ để cải thiện hiệu suất
      - discovery.type=single-node # Thiết lập chế độ single-node
      - action.auto_create_index=false # Vô hiệu hóa tự động tạo index
      - plugins.security.ssl.http.enabled=false # Vô hiệu hóa SSL cho HTTP
      - plugins.security.disabled=true # Vô hiệu hóa plugin bảo mật
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=Minhtenlaquang@123 # Mật khẩu khởi tạo cho user admin
    ulimits:
      memlock:
        hard: -1 # Thiết lập ulimit không giới hạn cho memlock
        soft: -1
      nofile:
        soft: 65536 # Thiết lập ulimit cho số lượng file mở tối đa
        hard: 65536
    volumes:
      - "opensearch_conf:/usr/share/opensearch/config/:rw" # Volume cho cấu hình OpenSearch
      - "opensearch_data:/usr/share/opensearch/data:rw" # Volume cho dữ liệu OpenSearch
    networks:
      - graylog_net
#    deploy:
#      resources:
#        limits:
#          cpus: "4.0"
#          memory: "6G"
#        reservations:
#          cpus: "2.0"
#          memory: "4G"
  mongodb:
    # Sử dụng image MongoDB phiên bản 7.0.14
    image: mongo:7.0.14
    container_name: mongodb
    volumes:
      - "mongodb_data:/data/db:rw" # Volume cho dữ liệu MongoDB
    restart: on-failure # Tự động khởi động lại nếu gặp lỗi
    #healthcheck:
    #  test: ["CMD-SHELL", "ping mongodb || exit 1"] # Kiểm tra trạng thái MongoDB
    #  interval: 30s # Thời gian giữa các lần kiểm tra
    #  timeout: 10s # Thời gian chờ cho mỗi lần kiểm tra
    #  retries: 5 # Số lần thử lại khi kiểm tra thất bại
    networks:
      - graylog_net

networks:
  graylog_net:
    driver: bridge # Sử dụng mạng bridge
#    deploy:
#      resources:
#        limits:
#          cpus: "1.0"
#          memory: "2G"
#        reservations:
#          cpus: "0.5"
#          memory: "1G"
volumes:
  graylog_data:
    driver: local # Volume cho dữ liệu Graylog
  opensearch_conf:
    driver: local # Volume cho cấu hình OpenSearch
  opensearch_data:
    driver: local # Volume cho dữ liệu OpenSearch
  mongodb_data:
    driver: local # Volume cho dữ liệu MongoDB
  graylog_plugin:
    driver: local # Volume cho journal của Graylog